### ISSUE TITLE
Publish to hex.pm

### ISSUE THREAD

**Issue by aberman** [ferd/erlpass#12]
Hey Fred,

Can you publish this to Hex?

Thanks!

**Comment by ferd** [comment]
I'll take note of it. I was on vacation away from a computer and will see when I can find time for it soon-ish.

**Comment by ferd** [comment]
In fact, I can't publish erlpass to hex because the bcrypt dependencies on there are too old. Can't do it for now.

**Comment by aberman** [comment]
Ok, no prob.

**Comment by ddeboer** [comment]
I worked together with the bcrypt Hex package’s previous owner and published a 1.0.0 version of bcrypt on Hex (based on https://github.com/erlangpack/bcrypt). This version is updated and compatible with OTP 20. 

@ferd Can you try to depend on `{bcrypt, "1.0.0"}` in your rebar.config? That should enable you to publish this package to Hex as well.

**Comment by ferd** [comment]
Looking at https://github.com/smarkets/erlang-bcrypt/compare/master...erlangpack:master you'll have a problem: the version being based on `git` means that when used as a package, all version information is dropped (since there's no git repo to read it from) and the `git` information of the importing codebase will be used. This means the hex versions and the runtime versions of the library will not match.

Once this is fixed, I could see it making sense to depend on that copy since it's otherwise in line with smarkets' version.

**Comment by ddeboer** [comment]
> the version being based on `git`

I used `{vsn, "git"}` so I can easily [auto-publish](https://github.com/zotonic/hexpub) the package from Travis to Hex.pm, based on its Git tag. This is want I want: Hex versions corresponding to Git tags.

What would be the recommended way to go about this? Change the version number in the `app.src` with `sed` or something like that?

**Comment by ferd** [comment]
I just double-checked, it appears that the publishing does make the version work by forcing it to be static. It's fine. The use case that causes problem is an alternative one and I got confused. The case where this fails is when someone downloads the .tar or some archive of the repo and builds from there -- this happened a lot with rebar3 itself.

**Comment by ddeboer** [comment]
I see. The idea here is to _only_ publish the package from Travis, where the environment is fully declared in `.travis.yml` so no weird stuff happens.

Unfortunately, I cannot find an e-mail address for smarkets/erlang-bcrypt’s original maintainer. He doesn’t seem to be active on GitHub anymore. I was able to reach chef/erlang-bcrypt’s maintainer to get owner rights on the bcrypt package on Hex. That that fork has already been deprecated.

So, at least we now have an up-to-date bcrypt version on Hex.pm. @ferd Are there any other issues you want resolved before depending on bcrypt 1.0?

**Comment by ferd** [comment]
That should be good enough, I think.

**Comment by ferd** [comment]
Done.
