### ISSUE TITLE
Switch to smarkets/bcrypt

### ISSUE THREAD

**Issue by ddeboer** [ferd/erlpass#13]
Would it be possible to switch the bcrypt dep from chef to [smarkets](https://github.com/smarkets/erlang-bcrypt)? It’s more up-to-date and it [compiles on Alpine](https://github.com/smarkets/erlang-bcrypt/issues/16), which is not the case for the chef version.

**Comment by ferd** [comment]
ugh, it used to be the opposite: https://github.com/ferd/erlpass/pull/4

I'd really enjoy if whoever maintains these libs worked together to keep one copy as authoritative.

**Comment by ddeboer** [comment]
Yeah, the wonders of open source. :wink:

**Comment by ferd** [comment]
Done!
