### ISSUE TITLE
updating bcrypt dependency?

### ISSUE THREAD

**Issue by peffis** [ferd/erlpass#16]
erlpass currently relies on a version of bcrypt that uses rand_bytes. Since rand_bytes is nowadays removed from OTP (in 20+) you are bound to OTP 19 if you want to use erlpass. 

There are however bcrypt versions made (mentioned in the issue on the bcrypt repo that erlpass is using) that has been updated to use strong_rand_bytes instead when compiled with OTP 20+. Is there any chance that erlpass could update its dependency to some updated bcrypt so that one could migrate an app using erlpass to something above OTP 19?

**Comment by ferd** [comment]
It needs to be a packaged version, otherwise I won't be able to re-publish a package of erlpass.

**Comment by peffis** [comment]
Not sure what you mean with packaged version to be honest, but there is a new repo for bcrypt now at https://github.com/erlangpack/bcrypt which works on OTP 20+. erlang.mk just updated its dependencies to use this version of bcrypt.

**Comment by peffis** [comment]
...or actually, just tried building erlpass again and rebar3 also pulls this new version of bcrypt so I guess problem is solved.
