### ISSUE TITLE
Unable to compile erlpass with rebar3

### ISSUE THREAD

**Issue by tuscland** [ferd/erlpass#6]
Hello Ferd,

`erlang-bcrypt` has been recently updated to support rebar3.
Would it be possible to point to the updated repository so `erlpass` can be compiled with rebar3 as well?

Thanks!

**Comment by ferd** [comment]
Oh good one yes. I'll try to take a look at this soon. Keeping this tab open.

**Comment by tuscland** [comment]
Hi @ferd,
Just wanted to check if you managed to find time to fix this...

**Comment by ferd** [comment]
I've got my provisional work in https://github.com/ferd/erlpass/pull/10 -- waiting to see what CI says.

**Comment by citrusO2** [comment]
Just as a reminder, with the latest update to support rebar3, rebar doesn't work anymore, so it is necessary to use "1.0.1" then

**Comment by ferd** [comment]
This should work, and packages are supported.
